/*
 *    Qizx Free_Engine-4.4p1
 *
 *    This code is part of Qizx XQuery engine
 *    Copyright (c) 2004-2010 Axyana Software -- All rights reserved.
 *
 *    For conditions of use, see the accompanying license files.
 */
package com.qizx.api;

/**
 * Interface for displaying execution traces generated by the XQuery function
 * fn:trace().
 */
public interface TraceObserver
{
    /**
     * Displays a single trace.
     * @param location place in source code where the trace is performed
     * @param label second argument of the fn:trace() function.
     * @param value first argument of the fn:trace() function.
     */
    void trace(EvaluationStackTrace location, ItemSequence value, String label);

}
